# Demonstrates import and random.choice
#
# EXPLANATION:
# This program simulates flipping a coin using the random module.
#
# KEY CONCEPTS:
# - The 'random' module provides functions for generating random numbers/choices
# - random.choice(list) picks a random element from a list
# - Each time you run the program, you might get a different result!
#
# HOW IT WORKS:
# 1. import random - loads the random module
# 2. random.choice(["heads", "tails"]) randomly picks one of the two options
# 3. The result is stored in 'coin' and printed
#
# RANDOMNESS IN PROGRAMMING:
# - Games: Random enemy spawns, dice rolls, card shuffles
# - Security: Generating passwords, tokens, encryption keys
# - Statistics: Sampling data, simulations
#
# OTHER RANDOM FUNCTIONS:
# - random.randint(a, b) - random integer between a and b
# - random.random() - random float between 0 and 1
# - random.shuffle(list) - randomly reorder a list
#
# IMPORTANT:
# Computer "randomness" is actually "pseudo-random" - it looks random
# but is generated by an algorithm. For most purposes, it's random enough!

import random

coin = random.choice(["heads", "tails"])
print(coin)
